### ISSUE TITLE
Crash when trying to create a new world

### ISSUE THREAD

**Issue by lightning02** [Mumfrey/LiteLoaderInstaller#10]
http://pastebin.com/0hbRMkRW
http://pastebin.com/u2etxJni

Btw I changed something after and I don't know if I'm able to reproduce it again, I even don't know what caused this.

**Comment by Mumfrey** [comment]
1. Wrong issue tracker, this is for the installer
2. It's bspkrscore, disable the "main menu mobs" in the config

**Comment by lightning02** [comment]
I will do! thanks :o
And sorry for the wrong issue tracker!! My fault
