### ISSUE TITLE
[1.10.2] Crash launching minecraft with liteloader and forge

### ISSUE THREAD

**Issue by Sir-Will** [Mumfrey/LiteLoaderInstaller#11]
hey,

I get this crash if I try to launch the 1.10.2 liteloader version with forge:
http://pastebin.com/raw/2L07KNmi

**Comment by Mumfrey** [comment]
Wrong issue tracker.

**Comment by Sir-Will** [comment]
I'm sorry, can you at least tell me which one is the correct one?

**Comment by liach** [comment]
http://develop.liteloader.com/liteloader/LiteLoader/issues

And by the way @Mumfrey IMO a link provided to that issue tracker in project readme might help people to report the issue without so many difficulties.
