### ISSUE TITLE
Ubuntu with openjdk7

### ISSUE THREAD

**Issue by ICHx** [Mumfrey/LiteLoaderInstaller#2]
I downloaded liteloader-installer-1.7.10-04.jar from homepage. The below log was shown while I don't know what happened. May please take a look.

--

$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

--

$ java -Xms256m -jar liteloader-installer-1.7.10-04.jar 
Error parsing gtk-icon-sizes string: ''
java.lang.ClassCastException: javax.swing.JSeparator cannot be cast to javax.swing.JPanel
	at com.mumfrey.liteloader.installer.gui.InstallerPanel.run(InstallerPanel.java:414)
	at com.mumfrey.liteloader.installer.Installer.main(Installer.java:62)
$
--

**Comment by rtsui-harmonicinc** [comment]
solved
