### ISSUE TITLE
Harvestcraft right-click harvesting broken when Liteloader installed

### ISSUE THREAD

**Issue by darthvader45** [Mumfrey/LiteLoaderInstaller#20]
https://github.com/MatrexsVigil/harvestcraft/issues/63

**Comment by Mumfrey** [comment]
This issue tracker is for the installer, please use the main issue tracker for issues with LiteLoader itself.

**Comment by darthvader45** [comment]
On CurseForge?  If not, link please?

**Comment by Zedrimar** [comment]
@darthvader45 it's been a fixed issue for a while now. It was something weird with forge and liteloader that went away after *2680 of forge 1.12.2

**Comment by darthvader45** [comment]
Huh, apparently it was just Harvestcraft's config.  Nvm.
