### ISSUE TITLE
Jar has a security seal for path but path is defined and not secure

### ISSUE THREAD

**Issue by DefinitelyNotFred** [Mumfrey/LiteLoaderInstaller#21]
My console gets a bunch of messages like in the title. There doesn't seem to be any actual problems when running Minecraft, though. I'm using Minecraft 1.12.2, MultiMC, and no mods for the time being.

Here's my log: https://pastebin.com/qpE63m73

**Comment by Mumfrey** [comment]
1. That issue is to do with running the game, nothing to do with the Installer.
2. Those warnings are simply generated when JInput is used at the same time as LaunchClassLoader due to the way that LWJGL is packaged.
