### ISSUE TITLE
Liteloader crashing with Forge 14.23.4.2760

### ISSUE THREAD

**Issue by darthvader45** [Mumfrey/LiteLoaderInstaller#22]
Seems that Liteloader is passing an extra --version when loading alongside the Forge version mentioned.  As a result it causes a major crash before the game can really even load, meaning I cannot play with both.

Way to replicate:

Install Forge 14.23.4.2760
Install Liteloader 1.12.2
Run MC, and crash.

**Comment by Blue-Beaker** [comment]
I find the same problem with MultiMC,which installs forge and liteloader automatically.
The game crashes before the game window came out.

**Comment by ScienceDrummer** [comment]
Really hope they get around to fixing this. Made an issue on their website and only got a response from one person. http://develop.liteloader.com/liteloader/LiteLoader/issues/61

**Comment by Mumfrey** [comment]
Hi, this issue tracker is for the installer not LiteLoader itself, I've responded on the Forge issue [here](https://github.com/MinecraftForge/MinecraftForge/issues/5207) explaining why the fix needs to be on Forge's end.
