### ISSUE TITLE
[suggestion] Please add version number to extracted liteloader.jar

### ISSUE THREAD

**Issue by Zedrimar** [Mumfrey/LiteLoaderInstaller#5]
In the next release can you add something at the end of liteloader to tell what version it is when you extract it, like "Liteloader-1.7.10_v5.jar" rather than just "Liteloader-1.7.10.jar"? I know I can do it my self, but not all catch on to this and when there is a fixed version some may wonder; "why is my mod pack crashing so much, its all Liteloader bugs" and come to find out that the bug(s) were fixed for a long time but they have an old version.

**Comment by Mumfrey** [comment]
I can definitely add this to the 1.8 versions going forward, 1.7.10 is on freeze unless a critical breaking change is made by Forge or something similar. Consider this accepted.

**Comment by Zedrimar** [comment]
awesome!
