### ISSUE TITLE
com.sun.java.swing.plaf.gtk.GTKLookAndFeel causes installer to crash

### ISSUE THREAD

**Issue by klugemonkey** [Mumfrey/LiteLoaderInstaller#9]
LiteLoaderInstaller 1.8.9 Build #4 failed to install on Debian x64 environment.

**java -jar liteloader-installer-1.8.9-00-SNAPSHOT.jar**

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
IllegalArgumentException: Version id does not match container in: /root/.minecraft/versions/1.8.9-LiteLoader/1.8.9-LiteLoader.json
IllegalArgumentException: Version id does not match container in: /root/.minecraft/versions/1.8.9-LiteLoader/1.8.9-LiteLoader.json
IllegalArgumentException: Version id does not match container in: /root/.minecraft/versions/1.8.9-LiteLoader/1.8.9-LiteLoader.json
IllegalArgumentException: Version id does not match container in: /root/.minecraft/versions/1.8.9-LiteLoader/1.8.9-LiteLoader.json
java.lang.ClassCastException: javax.swing.JSeparator cannot be cast to javax.swing.JPanel
    at com.mumfrey.liteloader.installer.gui.InstallerPanel.run(InstallerPanel.java:415)
    at com.mumfrey.liteloader.installer.Installer.main(Installer.java:61)
```

**uname -a**

```
Linux dev.concurable.com 4.5.0-kernel #1 SMP PREEMPT Mon Mar 28 00:52:43 PDT 2016 x86_64 GNU/Linux
```

**java -version**

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by Mumfrey** [comment]
I'll take a look into that for you.

**Comment by klugemonkey** [comment]
Thanks again,

Another question setting up the development environment on Eclipse. I 
understand the video is a bit outdated for this version.

I'm trying to use the 
http://develop.liteloader.com/liteloader/LiteLoader.git branch and when 
I get to the part about adding the ClassPath to the User Entries under 
the cloned Client config, it doesn't show the LiteLoader project for 
adding.

Any suggestions on how i should configure/add Launchwrapper class jar to 
the project?

kluge

**Comment by Mumfrey** [comment]
The new MDK eschews MCP in favour of gradle so the old tutorial isn't just outdated it is 100% utterly wrong and cannot be followed. I will be releasing the MDK pretty soon, but in a nutshell you no longer clone or build liteloader from source, you simply set up your gradle build script appropriately and everything else is handled automatically, _including_ setting up whatever IDE you're using.

**Comment by klugemonkey** [comment]
Thanks, I'll keep trying.  Let me know when MDK (mumfrey dev kit?) is 
available.
I'm looking forward to testing the 1.8.9 and also the 1.9 liteloader.

**Comment by Mumfrey** [comment]
MDK == "Mod Development Kit"

I anticipate it being completed within the next 1 to 2 weeks.

**Comment by klugemonkey** [comment]
Awesome.  I've been deprived of my worldedit cui since 1.9 and look 
forward to testing it.  Looks like you've been busy as well on the 
website.  Are you finding GitLab to be working well for you?

**Comment by Mumfrey** [comment]
Thanks to the verbosity of the output you posted, I was able to determine that the look-and-feel option is actually what is causing the crash, I can now troubleshoot this and find a fix.

**Comment by Mumfrey** [comment]
This should now be resolved, please try the new build available [here](http://jenkins.liteloader.com/view/1.8.9/job/LiteLoaderInstaller%201.8.9/5/)

**Comment by klugemonkey** [comment]
Had a feeling that that might be the issue

**Comment by klugemonkey** [comment]
Sweet.  Confirmed that GUI loads now on my system.  You totally rock!

kluge.
